version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: golang
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
